services:  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: blog_postgres
      POSTGRES_PASSWORD: blog_postgres
      POSTGRES_DB: blog_postgres
  
  # redis:
  #   image: "redis"
  #   ports:
  #     - 6379:6379